export const HOME_ORDERS_SETTLEMENT_PAGE_LIMIT = 100
export const HOME_ORDERS_FILLS_PAGE_LIMIT = 1000
export const HOME_ORDERS_EVENTS_PER_FETCH = 50
export const HOME_ORDERS_ROW_HEIGHT_PX = 118
export const HOME_ORDERS_SCROLL_LOAD_THRESHOLD_PX = 140
